
services:
  web_server:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html   # Monte le répertoire 'www' dans le conteneur Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Monte ta config Nginx
    networks:
      - webnet

  php_container:
    build: .
    image: php:7.4-fpm
    container_name: php_container
    volumes:
      - ./www:/var/www/html   # Assure-toi que PHP peut accéder à 'www'
    networks:
      - webnet

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory
    networks:
      - webnet
    volumes:
      - db_data:/var/lib/mysql

networks:
  webnet:
    driver: bridge

volumes:
  db_data:
